export type AgeGroupKey = "SEEDLING" | "SPROUT" | "SAPLING" | "TREE";

export const AGE_GROUPS = {
  SEEDLING: {
    id: "SEEDLING" as AgeGroupKey,
    label: "Seedling",
    wordsPerDay: 10,
    storyMinWords: 80,
    storyMaxWords: 120,
    ageMin: 4,
    ageMax: 6,
    emoji: "🌱",
    colour: "#86efac",
    description: "Simple nouns and adjectives",
  },
  SPROUT: {
    id: "SPROUT" as AgeGroupKey,
    label: "Sprout",
    wordsPerDay: 15,
    storyMinWords: 120,
    storyMaxWords: 180,
    ageMin: 6,
    ageMax: 8,
    emoji: "🌿",
    colour: "#4ade80",
    description: "Verbs, feelings, and nature words",
  },
  SAPLING: {
    id: "SAPLING" as AgeGroupKey,
    label: "Sapling",
    wordsPerDay: 20,
    storyMinWords: 180,
    storyMaxWords: 250,
    ageMin: 8,
    ageMax: 10,
    emoji: "🌳",
    colour: "#22c55e",
    description: "Abstract concepts and idioms",
  },
  TREE: {
    id: "TREE" as AgeGroupKey,
    label: "Tree",
    wordsPerDay: 25,
    storyMinWords: 250,
    storyMaxWords: 350,
    ageMin: 10,
    ageMax: 12,
    emoji: "🌲",
    colour: "#16a34a",
    description: "Formal vocabulary and metaphors",
  },
} as const;
